business/urls.py
from django.conf.urls import url
from views import PasswordForgotView, NewPasswordView

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^register/', 'business.views.register'),
    url(r'^register_floower/', 'business.views.register_follower'),
    url(r'^home/$', 'business.views.home'),
    url(r'^make_offer/', 'business.views.make_offer'),
    url(r'^login/', 'business.views.log_in', name='login'),
    url(r'^logout/', 'business.views.log_out'),
    url(r'^reset-password/$', PasswordForgotView.as_view(), name='reset-password'),
    url(r'^reset-password-form/(?P<email_hash>\S+)/$', NewPasswordView.as_view(), name='reset-password-form'),
    url(r'^$', 'landingpage.views.load_landing'),

]

salereporter/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^business/', include("business.urls")),
    url(r'^business/admin/', admin.site.urls),
    url(r'^business/testemail/', 'base.email.send_signup_mail'),
]

business/models.py
from __future__ import unicode_literals

from django.db import models
from base.models import BaseModel
from django.contrib.auth.models import User
from django.dispatch import receiver
from base import email

# Create your models here.
#business Type defination
# 1 = Restaurant 
# 2 = Bars 
# 3 = Grocery Stores 
# 4 = Department Stores 

@receiver(models.signals.pre_save)
def _user_activated(sender, instance, **kwargs):
    if sender == User:
        if instance.pk is not None:
        	user = User.objects.get(id=instance.pk)
        	if instance.pk is not None:
        		if user.is_active == False and instance.is_active == True:
        			try:
        				email.send_activation_mail(user.first_name, user.email)
        			except:
        				pass
        	




class Category(BaseModel):
	name = models.CharField(max_length=255)

class Business(BaseModel):
	first_name =  models.CharField(max_length=255)
	last_name =  models.CharField(max_length=255)
	title = models.CharField(max_length=255)
	phone_no = models.CharField(max_length=255)
	business_email = models.CharField(max_length=255)
	password = models.CharField(max_length=255)
	business_name = models.CharField(max_length=255)
	street = models.TextField()
	suite = models.CharField(max_length=255)
	city = models.CharField(max_length=255)
	state = models.CharField(max_length=255)
	business_phone = models.CharField(max_length=255)
	website = models.CharField(max_length=255)
	lat = models.CharField(max_length=255, default=None)
	longi = models.CharField(max_length=255, default=None)
	user = models.ForeignKey(User, default=None)
	business_type =  models.ForeignKey(Category, default=None)
	zip_code = models.CharField(max_length=255, default=None)
	def __unicode__(self):
		return self.first_name + " "+ self.last_name


class Follower(BaseModel):
	device_id = models.CharField(max_length=255, null=True)
	email = models.CharField(max_length=255, null=True)
	gcm_id = models.CharField(max_length=255, null=True)
	lat = models.CharField(max_length=255, null=True)
	longi = models.CharField(max_length=255, null=True)
	following = models.ManyToManyField(Business, default=None)
	pref_cat = models.ManyToManyField(Category, default=None)

class Offer(BaseModel):
	offer = models.CharField(blank=False,max_length=255)
	starts = models.CharField(blank=True, null=True, max_length=50)
	ends = models.CharField(blank=True, null=True, max_length=50)
	user = models.ForeignKey(User, default=None)

business/views.py
from django.shortcuts import render, render_to_response
from form import OfferForm, ForgotPasswordForm, NewPasswordForm
from django.core.context_processors import csrf
from django.contrib.auth.models import User
from models import Business, Offer, Category, Follower
from django.http.response import HttpResponseRedirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, hashers
from django.template import RequestContext
from django.contrib import auth
import ast
from django.views.decorators.csrf import csrf_exempt
import json
import math
import requests
from datetime import datetime
from django.contrib import messages
from base import email, reset_password
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import FormView
from django.core.urlresolvers import reverse

def distance_on_unit_sphere(lat1, long1, lat2, long2):
 
    # Convert latitude and longitude to 
    # spherical coordinates in radians.
    degrees_to_radians = math.pi/180.0
         
    # phi = 90 - latitude
    phi1 = (90.0 - lat1)*degrees_to_radians
    phi2 = (90.0 - lat2)*degrees_to_radians
         
    # theta = longitude
    theta1 = long1*degrees_to_radians
    theta2 = long2*degrees_to_radians
         
    # Compute spherical distance from spherical coordinates.
         
    # For two locations in spherical coordinates 
    # (1, theta, phi) and (1, theta', phi')
    # cosine( arc length ) = 
    #    sin phi sin phi' cos(theta-theta') + cos phi cos phi'
    # distance = rho * arc length
     
    cos = (math.sin(phi1)*math.sin(phi2)*math.cos(theta1 - theta2) + 
           math.cos(phi1)*math.cos(phi2))
    arc = math.acos( cos )
 
    # Remember to multiply arc by the radius of the earth 
    # in your favorite set of units to get length.
    return float(arc)*6378.1


# Create your views here.

def register(request):
	arg = {}
	arg.update(csrf(request))
	if request.method == 'POST':
		form_id = business_type = request.POST['form_id']
		if form_id == "1":
			request.session['business_type'] = request.POST['option']
			return render_to_response('business/b_company.html', arg)
		elif form_id == "2":
			request.session['first_name'] = request.POST['firstName']
			request.session['last_name'] = request.POST['lastName']
			request.session['title'] = request.POST['title']
			request.session['phone_no'] = request.POST['phone']
			request.session['business_email'] = request.POST['businessEmail']
			request.session['password'] = request.POST['password']
			if User.objects.filter(email=request.POST['businessEmail']).exists():
				arg['error'] = "Email already exists."
				arg['first_name'] = request.POST['firstName']
				arg['last_name'] = request.POST['lastName']
				arg['phone_no'] = request.POST['phone']
				arg['title'] = request.POST['title']
				arg['business_email'] = request.POST['businessEmail']
				return render_to_response('business/b_company.html', arg)
			return render_to_response('business/b_profile.html', arg)
		elif form_id == "3":
			first_name = request.session['first_name']
			last_name = request.session['last_name']
			title = request.session['title']
			phone_no = request.session['phone_no']
			business_email = request.session['business_email']
			password = request.session['password']
			lat = request.POST['lat']
			longi = request.POST['longi']
			business_name = request.POST['nameBusiness']
			street = request.POST['street']
			suite = request.POST['suite']
			city = request.POST['city']
			state = request.POST['state']
			zip_code = request.POST['zip']
			cat = Category.objects.get(id= request.session['business_type'])
			business_type = cat
			business_phone = request.POST['phoneNo']
			website = request.POST['website']
			# create user
			user = User.objects.create_user(business_email, business_email, password)
			user.last_name = last_name
			user.first_name = first_name
			user.is_active = False
			user.save()
			business = Business()
			business.first_name = first_name
			business.last_name = last_name
			business.title = title
			business.phone_no = phone_no
			business.business_email = business_email
			business.password = password
			business.business_name = business_name
			business.street = street
			business.suite = suite
			business.city = city
			business.state = state
			business.business_phone = business_phone
			business.website = website
			business.user = user
			business.business_type = business_type
			business.zip_code = zip_code
			business.lat = lat
			business.longi = longi
			business.save()
			try:
				email.send_signup_mail(first_name, business_email)
			except:
				pass
			messages.success(request, 'Thank you for registering. We appreciate your interest. Someone from our team will get back to you soon!')
			return HttpResponseRedirect('/business/login')
		return HttpResponse(business_type)
	return render_to_response('business/b_register.html', arg)

def log_in(request):
	""" This Function is used for user login """
	arg = {}
	arg.update(csrf(request))
	if request.user.is_authenticated():
		return HttpResponseRedirect('/business/home/')
	if request.POST:
		# redirect_to = request.REQUEST.get('next', '')
	    #username = password = ''
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is None:
			arg['error'] = "Invalid username or Password"
		elif user.is_active == False:
			arg['error'] = "User is not activated"
		else:
			login(request, user)
			return HttpResponseRedirect('/business/home')
	return render_to_response('business/login.html', arg, context_instance=RequestContext(request))
@login_required
def home(request):
	arg = {}
	arg['offers'] = Offer.objects.filter(user=request.user)
	return render_to_response('business/b_dashbrd.html', arg, context_instance=RequestContext(request))
@login_required
@csrf_exempt
def make_offer(request):
	arg = {}
	data = {}
	arg['form'] = OfferForm()
	arg['btn'] = 'Add'
	arg['cancel_url'] = '/business/home'
	arg.update(csrf(request))
	if request.method == 'POST':
		form = OfferForm(request.POST)
		arg['form'] = OfferForm(request.POST)
		if arg['form'].is_valid():
			form = OfferForm(request.POST)
			business = Business.objects.get(user=request.user)
			lat1 = float(business.lat)
			long1 = float(business.longi)
			gsm_ids = []
			followers = Follower.objects.all()
			for follower in followers:
				if follower.lat != None and follower.longi != None:
					lat2 = float(follower.lat)
					lobg2 = float(follower.longi)
					#calculate the distance and add to list if distance is less than 50k
					distance = distance_on_unit_sphere(lat1, long1, lat2, lobg2)
					business_cat = business.business_type
					follower_cat = follower.pref_cat.all()
					if distance < 50.0 and business_cat in follower_cat:
						gsm_ids.append(follower.gcm_id)
				else:
					#add to list if location data not found
					gsm_ids.append(follower.gcm_id)
			message = request.POST['offer']
			starts = request.POST['starts']
			ends = request.POST['ends']
			date =datetime.strptime(ends, "%Y/%m/%d %I:%M %p")
			business_address = business.business_name+", "+business.street+", "+business.city+", "+ business.state
			
			item = {"data": {"message": ""+message+ " till "+date.strftime("%I:%M %p on %B %d, %Y")+" at "+business_address ,}}
			item['registration_ids'] = gsm_ids
			item['content_available'] = True

			noti = {}
			noti['content_available'] = True
			noti['notification'] = {}
			noti['notification']['body'] = message+ " till "+date.strftime("%I:%M %p on %B %d, %Y")+" at "+business_address
			noti['data'] = {}
			noti['data']['message'] = message+ " till "+date.strftime("%I:%M %p on %B %d, %Y")+" at "+business_address
			noti['data']['title'] = "New Offer"
			noti['notification']['sound'] = 'default'
			noti['registration_ids'] = gsm_ids
            data['tokens'] = gsm_ids
			noti['priority'] = 'high'
            # main API AIzaSyBgjSTNM-AWHovf25d6mrmX7No23yycWqk
			#return HttpResponse(json.dumps(item), content_type="application/json")
			resp = requests.post("https://gcm-http.googleapis.com/gcm/send", data=json.dumps(noti),headers={"Content-Type":"application/json",'Authorization': 'key=%s' % "AIzaSyB2R4E6G6cR9tD3jdpEVhzaA59AGBWZI1k"})
			obj = arg['form'].save(commit=False)
			obj.user = request.user
			obj.save()
           
			data['status'] ="success"
		else:
			data['status'] ="falure"
		return HttpResponse(json.dumps(data), content_type="application/json")
	return render_to_response('business/b_offer.html', arg, context_instance=RequestContext(request))
def log_out(request):
	return render_to_response('business/b_offer.html', arg, context_instance=RequestContext(request))
def log_out(request):
	auth.logout(request)
	return HttpResponseRedirect("/business/login")




@csrf_exempt
def register_follower(request):
	arg = {}
	if request.POST:
		email = request.POST['email']
		gcm_id = request.POST['gcm_id']
		lat = request.POST['lat']
		longi = request.POST['longi']
		device_id = request.POST['device_id']
		preff = request.POST['preff']
		if device_id != "":
			try:
			    follower = Follower.objects.get(device_id=device_id)
			except Follower.DoesNotExist:
			    follower = Follower(device_id=device_id)
			    follower.save()
			if email != "":
				follower.email = email
			if gcm_id != "":
				follower.gcm_id = gcm_id
			if lat != "":
				follower.lat = lat
			if longi != "":
				follower.longi = longi
			if preff != "":
				preff_list = json.loads(preff)
				for cat_id in preff_list:
					try:
						cat = Category.objects.get(id=cat_id)
						follower.pref_cat.add(cat)
					except:
						pass
			follower.save()
			arg['status'] = "success"
		else:
			arg['status'] = "failure"
	return HttpResponse(json.dumps(arg), content_type="application/json")
# def follow_resturent(request):

class PasswordForgotView(FormView):

business/templates/business/b_company.html
{% extends "base/layout.html" %}
{% load staticfiles %}
{% block title %}
Salereporter | Register
{% endblock %}
{% block nav %}
	{% include "business/nav_register.html" %}
{% endblock %}
{% block extrameta %}
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'business/css/formValidation.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'maps/css/jquery-gmaps-latlon-picker.css' %}"/>
{% endblock %}
{% block content %}
	 <div class="container">
        	<div class="row">
        		<div class="col-sm-12">
                	<h3 class="text-center">Business Contact</h3>
                </div>
        	</div>
        
	    	<div class="row">
	    		<div class="col-sm-8 col-sm-offset-2">
	    			{% if error %}
	    			<div class="alert alert-danger fade in">
					    <a href="#" class="close" data-dismiss="alert">&times;</a>
					    <strong>Error!</strong> {{ error }}
					</div>
					{% endif %}
                	<form id="defaultForm" action="" method="post">
                		{% csrf_token %}
				        <input type="hidden" name="form_id" value="2"> 
	                	<div class="panel panel-default">	
                        	<div class="panel-body">                        	
                            	<div class="row">
                            		<div class="col-sm-6">
                                    	<div class="form-group">
                                        	<input type="text" class="form-control" name="firstName" placeholder="First Name" value="{{ first_name }}">
                                        </div>
                                    </div>
                                    
                                    <div class="col-sm-6">
                                    	<div class="form-group">
                                        	<input type="text" class="form-control" name="lastName" placeholder="Last name" value="{{ last_name }}" />
                                        </div>
                                    </div>
                            	</div>
                                
                                <div class="row">
		                    		<div class="col-sm-6">
		                            	<div class="form-group">
                                            <input type="text" name="title" class="form-control" placeholder="Title" value="{{ title }}">
                                        </div>
		                            </div>
		                    		<div class="col-sm-6">
                                    	<div class="form-group">
                                            <input type="text" name="phone" class="form-control" placeholder="Phone" value="{{ phone_no }}">
                                        </div>
		                            </div>
		                    	</div>
                                
                                <div class="row">
                                	<div class="col-sm-12">
                                    	<div class="form-group">
                                            <input type="email" name="businessEmail" class="form-control" placeholder="Business Email" value="{{ business_email }}">
                                        </div>
                                    </div>                                	
                                </div>
                                
		                    	<div class="row">
		                    		<div class="col-sm-12">
                                    	<div class="form-group">
                                            <input type="password" name="password" class="form-control" placeholder="Password">
                                        </div>
                                    </div> 
		                    	</div>                          	
                         </div> 
            			</div>                         	
                        <button type="submit" name="submitButton" class="btn btn-info center-block mt25">Next</button>
                    </form>     
                	
                </div>
	    	</div>
	    </div>
        
{% endblock %}
{% block extrajs %}
<script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script src="{% static 'maps/js/jquery-gmaps-latlon-picker.js' %}"></script>
<script type="text/javascript" src="{% static 'business/js/formValidation.js' %}"></script>
<script type="text/javascript" src="{% static 'business/js/framework/bootstrap.js' %}"></script>
<script type="text/javascript">
			$(document).ready(function() {
			    // Generate a simple captcha
			    function randomNumber(min, max) {
			        return Math.floor(Math.random() * (max - min + 1) + min);
			    };
			    $('#captchaOperation').html([randomNumber(1, 100), '+', randomNumber(1, 200), '='].join(' '));
			
			    $('#defaultForm').formValidation({
			        message: 'This value is not valid',
			        icon: {
			            valid: 'glyphicon glyphicon-ok',
			            invalid: 'glyphicon glyphicon-remove',
			            validating: 'glyphicon glyphicon-refresh'
			        },
			        fields: {
			            firstName: {
			                row: '.col-sm-6',
			                validators: {
			                    notEmpty: {
			                        message: 'The first name is required'
			                    }
			                }
			            },
			            lastName: {
			                row: '.col-sm-6',
			                validators: {
			                    notEmpty: {
			                        message: 'The last name is required'
			                    }
			                }
			            },
						title: {
			                row: '.col-sm-6',
			                validators: {
			                    notEmpty: {
			                        message: 'The title is required'
			                    }
			                }
			            },
			            phone: {
			                row: '.col-sm-6',
			                validators: {
			                    notEmpty: {
			                        message: 'The phone is required'
			                    },
			                    phone: {
                            		country: 'US',
                            		message: 'The value is not valid %s phone number'
                        		}
			                }
			            },	
						businessEmail: {
			                validators: {
			                    notEmpty: {
			                        message: 'The business email address is required'
			                    },
			                    regexp: {
			                    	regexp: /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,3}))$/,
			                        message: 'The input is not a valid email address'
			                    }
			                }
			            },
			            password: {
			                validators: {
			                    notEmpty: {
			                        message: 'The password is required'
			                    },
			                    different: {
			                        field: 'username',
			                        message: 'The password cannot be the same as username'
			                    }
			                }
			            },	            
			        }
			    });
			});
		</script>
{% endblock %}   

business/templates/business/b_dashbrd.html
{% extends "base/layout.html" %}
{% load staticfiles %}
{% block title %}
Business Dashboard | Salereporter
{% endblock %}
{% block nav %}
    {% include "base/nave_top.html" %}
{% endblock %}
{% block extrameta %}
<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		
		<!-- Bootstrap -->
		<link href="{% static 'business/css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'business/css/custom.css' %}" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'business/css/formValidation.css' %}"/>
        <link href="{% static 'business/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
		
		<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		      
	
	    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
	    <script src="{% static 'base/js/vendor/bootstrap.min.js' %}"></script>
	    <script type="text/javascript" src="{% static 'business/js/formValidation.js' %}"></script>
		<script type="text/javascript" src="{% static 'business/js/framework/bootstrap.js' %}"></script>
		
{% endblock %}
{% block content %}
	    <div class="container">
        	<div class="row">
        		<div class="col-sm-12">
                	<h3 class="text-center">Offer History</h3>
                </div>
        	</div>
        
	    	<div class="row">
	    		<div class="col-sm-4">
                	<a href="/business/make_offer" class="btn btn-lg btn-default btn-block">Offer Sale</a>
                </div>
                <div class="col-sm-8">
                	<div class="panel panel-default">
                		<div class="panel-body">
                        	<div class="comments-list">
                        		{% for offer in offers %}
			                   	<div class="media">
			                    	<p class="pull-right"><small>{{ offer.starts }} </small></p>
			                        <div class="media-body">			                                
										<h4 class="media-heading user_name">{{ offer.offer }}</h4>
									</div>
			                  	</div>
			                  	{% endfor %}
			        
			               	</div>
                        </div>
                	</div>
                </div>
	    	</div>
	    </div>
{% endblock %}

business/templates/business/b_forgot_password.html
{% extends "base/layout.html" %}
{% block title %}
Salereporter | Login
{% endblock %}
{% block extracss %}
<style type="text/css">
body {
    background: #ccc;
}

  .form-signin {
    max-width: 280px;
    margin: 60px auto 10px;
  }

  .form-signin .checkbox {
    font-weight: normal;
  }

  .form-signin .form-control {
    position: relative;
    font-size: 16px;
    height: auto;
    padding: 10px;
  }

  .form-signin input[type="text"] {
    margin-bottom: -1px;
    border-top: 1px solid transparent;
    border-right: 1px solid transparent;
    border-left: 1px solid transparent;
    box-shadow: none;
    border-radius: 3px 3px 0px 0px;
  }

  .form-signin input[type="text"]:focus {
    /*box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);*/
  }

  .form-signin input[type="password"] {
    z-index: 2;
    margin-bottom: 20px;
    border-top: none;
    border-bottom: 1px solid transparent;
    border-right: 1px solid transparent;
    border-left: 1px solid transparent;
    border-radius: 0px 0px 3px 3px;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  }

  .form-signin input[type="password"]:focus {
    /*box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0px 1px 0px 0px rgba(255, 255, 255, 0.5);*/
  }

</style>
{% endblock %}
{% block nav %}
  {% include "business/nav_register.html" %}
{% endblock %}
{% block content %}
  <div class="container">
    {% if messages %}
    {% for message in messages %}
    <center><h3 style="color: #26A65B; font-size: 18px;" class="{{ message.tags }}">{{ message }}</h3></center>
    {% endfor %}
{% endif %}
    <form action="" method="post" class="form-signin">
      <h3>Reset Password</h3>
    <div class="form-error">
        <span style="color: red;">{{ error }}</span>
    </div>
      {% csrf_token %}
        <span style="color: red;">{{ form.email.errors.as_text }}</span>
        {{ form.email }}
        
           <button class="btn btn-default hb-mt-15 center-block btn-block btn-lg" type="submit">Send</button> 
      </h3>Not a Registered? Plese <a href="/business/register/" >Sign Up</a></h3>
      </form>
  </div>
{% endblock %}
{% block footer %}
{% endblock %}

business/templates/business/b_offer.html
{% extends "base/layout.html" %}
{% block title %}
Launch Sale | Salereporter
{% endblock %}
{% load staticfiles %}
{% block nav %}
	{% include "base/nave_top.html" %}
{% endblock %}
{% block extrameta %}
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'business/css/formValidation.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'business/css/jquery.datetimepicker.css' %}"/>
<script src="{% static 'business/js/sweetalert.js' %}"></script>
<link rel="stylesheet" href="{% static 'business/css/sweetalert.css' %}">
{% endblock %}
{% block content %}


<div class="container">
        	<div class="row">
        		<div class="col-sm-12">
                	<h3 class="text-center">What are you offering?</h3>
                </div>
        	</div>       
	    	<div class="row">
	    		<div class="col-sm-8 col-sm-offset-3">
                	<div class="panel panel-default">
                		<div class="panel-body">
                			<span class="error_message errors"></span>
                        	<form name="myOffer"  method="post" action="">
                        		{% csrf_token %}
	                          <div class="form-group">
	                              {{ form.starts.errors }}
	  					          {{ form.offer }}
	                          </div>
	                          <div class="row">
	                              <div class="col-sm-6">
	                                  <div class="form-group">
	                                  	{{ form.starts.errors }}
	  					                {{ form.starts }}
	  									<br/>
	  					            </div>
	                              </div>
	                              <div class="col-sm-6">
	                              	<div class="form-group">
	                              		{{ form.ends.errors }}
	  					                {{ form.ends }}
	  					               <br/>
	  					            </div>
	                              </div>
	                          </div>
	                          <span type="submit" id="submit" class="btn btn-block btn-success sweet-12"  >Launch Sale</span>
	                          
	                      </form>	
                        </div>
                	</div>
                </div>
	    	</div>
	    </div>
	           
{% endblock %}
{% block extrajs %}
		<script src="{% static 'business/js/jquery.datetimepicker.js' %}"></script>
	  
		<script type="text/javascript">

		$("#submit").bind('click',function(){
			  			var offer = $('#id_offer').val();
  						var starts = $('#id_starts').val();
  						var ends = $('#id_ends').val();
  						if(offer == '' || starts == '' || ends==''){
  							alert("All Fields required")
  							return;
  						}
   			$.post( "/business/make_offer/", {offer: offer, starts: starts, ends: ends}, function(data) {
				if(data['status'] == 'success'){
				    console.log(data);
					$('#id_offer').val('');
                 } else {
					alert("Sorry, something wrong")
				}
			});
		});
			$('#id_starts').datetimepicker({
					    format:'Y/m/d h:i A',
					    timepicker: true, // use timepicker
					    formatTime: 'g:i A',
					    minDate: 0,
					    minTime: 0,
					    onChangeDateTime:function(dp,$input){
                		var date = Date.parse($('#id_starts').val());
		                var hours = 3*3600*1000;
		                var end_date = date + hours;
		   				var end_date = new Date(end_date);
		   				$('#id_ends').val('');
		   							$('#id_ends').datetimepicker({
									    format:'Y/m/d h:i A',
									    timepicker: true, // use timepicker
									    formatTime: 'g:i A',
									    value: end_date,
									    maxDate: end_date,
			    					    minDate: 0,
					   					minTime: 0,
					    				});
                            }
					    });
			$('#id_ends').datetimepicker({
					    format:'Y/m/d h:i A',
					    timepicker: true, // use timepicker
					    formatTime: 'g:i A',
					    });
		function s_laert(){
			swal({
			      title: "Your offer has started",
			      text: "People in the area have been notified",
			      type: "success",
			      showCancelButton: false,
			      confirmButtonClass: 'btn-success',
			      confirmButtonText: 'Close'},
			      function(isConfirm) {
				  if (isConfirm) {
				    window.location.href = "http://salereporter.com/business/home/";
				  }
			      });
			}							
			    	
		</script>
{% endblock %}

business/templates/business/nav_register.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/business/home/">Salereporter</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
    <li><a href="/business/login">Login</a></li>
  </u>
  </div>
</nav>